import unittest

import datetime

from digitalreleases2 import compile_html


class TetsCaseCompile(unittest.TestCase):

    def test_jinja2func(self):
        movies = [{'filmID': '908691', 'nameRU': 'Шафт', 'nameOriginal': 'Shaft', 'description': 'Джон Шафт III — специалист по кибербезопасности в ФБР, не привыкший решать проблемы грубой силой. Он предпочитает полагаться на логику и расчёт, но убийство лучшего друга ставит его в тупик. С ним не разобраться современными методами, так что Джону ничего не остается, кроме как обратиться за помощью к старшему поколению Шафтов, чьи старые методы помогут ему найти убийцу.', 'year': '2019', 'country': 'США', 'genre': 'боевик, комедия, криминал', 'ratingAgeLimits': '', 'ratingMPAA': 'R', 'posterURL': 'https://st.kp.yandex.net/images/film_iphone/iphone_908691.jpg?d=20190211091639&width=360', 'filmLength': '1:51', 'ratingKP': '', 'ratingIMDb': '6.2', 'rating': '6.2', 'ratingFloat': 6.2, 'directors': 'Тим Стори', 'actors': 'Сэмюэл Л. Джексон, Джесси Ашер, Ричард Раундтри', 'webURL': 'http://www.kinopoisk.ru/film/908691/', 'premierDate': datetime.date(2019, 6, 14), 'premierType': 'world', 'torrents': [{'link': 'http://d.rutor.info/download/706387', 'magnet': 'magnet:?xt=urn:btih:e4cf9d993e1ad22e05de834210227476c114a10a&dn=rutor.info&tr=udp://opentor.org:2710&tr=udp://opentor.org:2710&tr=http://retracker.local/announce', 'date': datetime.date(2019, 6, 28), 'type': 'WEB-DL 1080p'}], 'torrentsDate': datetime.date(2019, 6, 28)},
                  {'filmID': '841636', 'nameRU': 'Дамбо', 'nameOriginal': 'Dumbo', 'description': 'Цирковой импресарио Макс Медичи назначает бывшую звезду цирка Холта Фэрриера и его детей Милли и Джо опекунами новорожденного слонёнка, чьи невероятно большие уши сразу становятся предметом для постоянных шуток и насмешек коллег Холта по цеху. Внезапно узнав, что Дамбо умеет летать, владелец цирка решает нажиться на необычных способностях слонёнка. К делу подключается энергичный предприниматель В.А.Вэндевер, который решает сделать из малыша Дамбо главную звезду своего нового грандиозного развлекательного предприятия «Сказочная страна».', 'year': '2019', 'country': 'США', 'genre': 'фэнтези, семейный', 'ratingAgeLimits': '6', 'ratingMPAA': 'PG', 'posterURL': 'https://st.kp.yandex.net/images/film_iphone/iphone_841636.jpg?d=20190207130719&width=360', 'filmLength': '1:52', 'ratingKP': '7.0', 'ratingIMDb': '6.5', 'rating': '6.8', 'ratingFloat': 6.8, 'directors': 'Тим Бёртон', 'actors': 'Колин Фаррелл, Майкл Китон, Дэнни ДеВито', 'webURL': 'http://www.kinopoisk.ru/film/841636/', 'premierDate': datetime.date(2019, 3, 28), 'premierType': 'ru', 'torrents': [{'link': 'http://d.rutor.info/download/706278', 'magnet': 'magnet:?xt=urn:btih:089bc4cdc9bb7281235fe0b561e700764dbae755&dn=rutor.info&tr=udp://opentor.org:2710&tr=udp://opentor.org:2710&tr=http://retracker.local/announce', 'date': datetime.date(2019, 6, 27), 'type': 'BDRip 1080p'}, {'link': 'http://d.rutor.info/download/706308', 'magnet': 'magnet:?xt=urn:btih:807899de24beff76a7f151eadfaa809df310627b&dn=rutor.info&tr=udp://opentor.org:2710&tr=udp://opentor.org:2710&tr=http://retracker.local/announce', 'date': datetime.date(2019, 6, 28), 'type': 'BDRip-HEVC 1080p'}, {'link': 'http://d.rutor.info/download/706280', 'magnet': 'magnet:?xt=urn:btih:5eea8d03ea5274a2689bee715c9a1b4ecdc3a4b7&dn=rutor.info&tr=udp://opentor.org:2710&tr=udp://opentor.org:2710&tr=http://retracker.local/announce', 'date': datetime.date(2019, 6, 27), 'type': 'BDRemux'}, {'link': 'http://d.rutor.info/download/706282', 'magnet': 'magnet:?xt=urn:btih:cf19e161bec9ad3f30605557e3e0e6f1c3f551db&dn=rutor.info&tr=udp://opentor.org:2710&tr=udp://opentor.org:2710&tr=http://retracker.local/announce', 'date': datetime.date(2019, 6, 27), 'type': 'UHD BDRemux HDR'}], 'torrentsDate': datetime.date(2019, 6, 27)}]
        result = compile_html({"name": "user"}, '')
        self.assertEqual("user", result)

